[package]
name = "chunk_ipfss"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.10"
derive_builder = "0.12"
sha2 = "0.10"
hex = "0.4"
ipfs-api = "0.17"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"